# Generated by Django 3.1.14 on 2022-02-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('apis_metainfo', '0002_auto_20220201_1241'),
        ('apis_labels', '0002_auto_20220201_1241'),
        ('apis_relations', '0002_property_property_class_uri'),
        ('apis_ontology', '0005_delete_resource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContributionNew',
            new_name='Contribution',
        ),
        migrations.RenameModel(
            old_name='IdentifierNew',
            new_name='Identifier',
        ),
        migrations.RenameModel(
            old_name='InstanceNew',
            new_name='Instance',
        ),
        migrations.RenameModel(
            old_name='ItemNew',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='PersonNew',
            new_name='Person',
        ),
        migrations.RenameModel(
            old_name='RoleNew',
            new_name='Role',
        ),
        migrations.RenameModel(
            old_name='WorkNew',
            new_name='Work',
        ),
    ]
