# Generated by Django 3.1.14 on 2022-12-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_relations', '0002_property_property_class_uri'),
        ('apis_labels', '0002_auto_20220201_1241'),
        ('apis_metainfo', '0003_auto_20220218_1530'),
        ('apis_ontology', '0007_auto_20221130_0717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
