# Generated by Django 4.1.10 on 2023-07-06 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0009_place"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contribution",
        ),
    ]
