# Generated by Django 4.1.10 on 2023-07-06 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0011_delete_identifier"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
