# Generated by Django 4.1.10 on 2023-07-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0014_remove_instance_citation_instance_comments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="subject",
        ),
        migrations.AddField(
            model_name="person",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="subject",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="subject"
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="external_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
