# Generated by Django 4.1.10 on 2023-07-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0014_person_comments_person_external_link_person_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="external_link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
