# Generated by Django 4.1.10 on 2023-07-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apis_ontology",
            "0015_remove_work_subject_person_comments_person_subject_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="subject",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="subject"
            ),
        ),
    ]
