# Generated by Django 4.1.10 on 2023-07-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0016_work_comments_work_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="subject",
        ),
        migrations.AddField(
            model_name="person",
            name="external_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="external_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
