# Generated by Django 4.1.10 on 2023-07-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0018_alter_instance_set_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
