# Generated by Django 4.1.10 on 2023-09-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0019_place_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instance",
            name="tibschol_ref",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
    ]
