# Generated by Django 4.1.10 on 2023-09-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0022_instance_sde_dge_ref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="sde_dge_ref",
        ),
        migrations.AddField(
            model_name="work",
            name="sde_dge_ref",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
