# Generated by Django 4.1.12 on 2023-10-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0024_alter_instance_alternative_names_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="availability",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lost", "lost"),
                    ("available", "available"),
                    ("non-accessible", "non-accessible"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="nationality",
            field=models.CharField(
                blank=True,
                choices=[("Indic", "Indic"), ("Tibetan", "Tibetan")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="existance",
            field=models.CharField(
                blank=True,
                choices=[("extant", "extant"), ("non-extant", "non-extant")],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="original_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sanskrit", "Sanskrit"),
                    ("Tibetan", "Tibetan"),
                    ("Tangut", "Tangut"),
                    ("Other", "Other"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
