# Generated by Django 4.1.10 on 2023-09-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0024_alter_instance_alternative_names_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="zotero_ref",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
