# Generated by Django 4.1.12 on 2023-10-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0025_instance_availability_person_nationality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="item_descriptipn",
            field=models.TextField(
                blank=True, null=True, verbose_name="Item description"
            ),
        ),
    ]
