# Generated by Django 4.1.12 on 2023-10-05 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0026_instance_item_descriptipn"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instance",
            old_name="item_descriptipn",
            new_name="item_description",
        ),
    ]
