# Generated by Django 4.1.12 on 2023-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0027_rename_item_descriptipn_instance_item_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="existance",
        ),
        migrations.AddField(
            model_name="work",
            name="isExtant",
            field=models.BooleanField(default=True, verbose_name="Is extant"),
        ),
    ]
