# Generated by Django 4.1.12 on 2023-10-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0028_remove_work_existance_work_isextant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="tibschol_ref",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tibschol reference"
            ),
        ),
    ]
