# Generated by Django 4.1.11 on 2023-10-16 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0025_instance_zotero_ref"),
        ("apis_ontology", "0029_alter_instance_tibschol_ref"),
    ]

    operations = []
