# Generated by Django 4.1.13 on 2023-11-13 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '__first__'),
        ('apis_ontology', '0030_merge_20231016_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAuthorOfWork',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            bases=('relations.relation',),
        ),
    ]
