# Generated by Django 4.1.13 on 2023-11-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0032_personauthorofwork_support_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personauthorofwork',
            name='support_text',
        ),
        migrations.AddField(
            model_name='personauthorofwork',
            name='confidence',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Uncertain', 'Uncertain'), ('Negative', 'Negative')], max_length=1000, null=True, verbose_name='Confidence'),
        ),
        migrations.AddField(
            model_name='personauthorofwork',
            name='support_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Support notes'),
        ),
        migrations.AlterField(
            model_name='personauthorofwork',
            name='tei_refs',
            field=models.TextField(blank=True, null=True, verbose_name='Excerpts'),
        ),
        migrations.AlterField(
            model_name='personauthorofwork',
            name='zotero_refs',
            field=models.TextField(blank=True, null=True, verbose_name='Zotero'),
        ),
    ]
