# Generated by Django 2.2.11 on 2021-07-21 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis_metainfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempEntityClass',
            fields=[
                ('rootobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.RootObject')),
                ('review', models.BooleanField(default=False, help_text='Should be set to True, if the data record holds up quality standards.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_start_date', models.DateField(blank=True, null=True)),
                ('start_end_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_start_date', models.DateField(blank=True, null=True)),
                ('end_end_date', models.DateField(blank=True, null=True)),
                ('start_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='Start')),
                ('end_date_written', models.CharField(blank=True, max_length=255, null=True, verbose_name='End')),
                ('status', models.CharField(max_length=100)),
                ('references', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('collection', models.ManyToManyField(to='apis_metainfo.Collection')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_metainfo.Source')),
                ('text', models.ManyToManyField(blank=True, to='apis_metainfo.Text')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_metainfo.rootobject',),
        ),
        migrations.CreateModel(
            name='Auffuehrung',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='Aufzeichnung',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='E1_Crm_Entity',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
                ('note', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='Einteiliges_Work',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='Ereignis',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='F9_Place',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
                ('kapitelnummer', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='Inszenierung',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='Kapitel',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
                ('kapitel_nummer', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='Performatives_Work',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='Sammelwerk',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='Textausschnitt',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.TempEntityClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='E55_Type',
            fields=[
                ('e1_crm_entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.E1_Crm_Entity')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.e1_crm_entity',),
        ),
        migrations.CreateModel(
            name='F10_Person',
            fields=[
                ('e1_crm_entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.E1_Crm_Entity')),
                ('role', models.CharField(blank=True, max_length=1024, null=True)),
                ('forename', models.CharField(blank=True, help_text='The persons´s forename. In case of more then one name...', max_length=255, null=True, verbose_name='Vorname')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nachname')),
                ('name_generisch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name generisch')),
                ('vorname_zweitansetzung', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vorname (Zweitansetzung)')),
                ('nachname_zweitansetzung', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nachname (Zweitansetzung)')),
                ('name_generisch_zweitansetzung', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name generisch (Zweitansetzung)')),
                ('gender', models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male'), ('third gender', 'third gender')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.e1_crm_entity',),
        ),
        migrations.CreateModel(
            name='F1_Work',
            fields=[
                ('e1_crm_entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.E1_Crm_Entity')),
                ('untertitel', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Untertitel')),
                ('anmerkung', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Anmerkung')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.e1_crm_entity',),
        ),
        migrations.CreateModel(
            name='F2_Expression',
            fields=[
                ('e1_crm_entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.E1_Crm_Entity')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.e1_crm_entity',),
        ),
        migrations.CreateModel(
            name='F4_Manifestation_Singleton',
            fields=[
                ('e1_crm_entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.E1_Crm_Entity')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.e1_crm_entity',),
        ),
    ]
