# Generated by Django 3.1.14 on 2022-02-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xml_file',
            name='file_content',
            field=models.TextField(blank=True),
        ),
    ]
