# Generated by Django 3.1.14 on 2023-03-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
