# Generated by Django 3.1.14 on 2022-03-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0002_xml_file_file_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='F21_Recording_Work',
            fields=[
                ('f1_work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.f1_work')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.f1_work',),
        ),
        migrations.CreateModel(
            name='F26_Recording',
            fields=[
                ('f1_work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.f1_work')),
                ('airing_date', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.f1_work',),
        ),
    ]
