# Generated by Django 3.1.14 on 2022-02-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0002_auto_20220215_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='F31_Performance',
            fields=[
                ('f1_work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.f1_work')),
                ('note', models.CharField(blank=True, max_length=1024, null=True)),
                ('category', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.f1_work',),
        ),
        migrations.RemoveField(
            model_name='f20_performance_work',
            name='category',
        ),
        migrations.RemoveField(
            model_name='f20_performance_work',
            name='note',
        ),
    ]
