# Generated by Django 3.1.14 on 2022-03-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0003_f21_recording_work_f26_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='f1_work',
            name='index_in_chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
