# Generated by Django 3.1.14 on 2022-03-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0006_chapter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='F1_Work',
            name='short',
            field=models.CharField(blank=True, max_length=1024, null=True)
        ),
        migrations.AddField(
            model_name='F3_Manifestation_Product_Type',
            name='short',
            field=models.CharField(blank=True, max_length=1024, null=True)
        ),
        migrations.AddField(
            model_name='F26_Recording',
            name='broadcast_id',
            field=models.CharField(blank=True, max_length=1024, null=True)
        ),
        migrations.AddField(
            model_name='F31_Performance',
            name='performance_id',
            field=models.CharField(blank=True, max_length=1024, null=True)
        ),
        migrations.AddField(
            model_name='F31_Performance',
            name='performance_type',
            field=models.CharField(blank=True, max_length=1024, null=True)
        ),
        migrations.AddField(
            model_name='E40_Legal_Body',
            name='institution_id',
            field=models.CharField(blank=True, max_length=1024, null=True)
        ),
    ]
