# Generated by Django 3.1.14 on 2022-03-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        
        ('apis_ontology', '0009_genres_for_f1_work'),
    ]

    operations = [
        
        # migrations.AddField(
        #     model_name='F1_Work',
        #     name='note',
        #     field=models.CharField(blank=True, max_length=1024, null=True)
        # ),
        migrations.AddField(
            model_name='F3_Manifestation_Product_Type',
            name='untertitel',
            field=models.CharField(blank=True, max_length=1024, null=True)
        ),
        migrations.AddField(
            model_name='F3_Manifestation_Product_Type',
            name='page',
            field=models.CharField(blank=True, max_length=1024, null=True)
        ),
        migrations.AddField(
            model_name='F3_Manifestation_Product_Type',
            name='issue',
            field=models.CharField(blank=True, max_length=1024, null=True)
        ),
        migrations.AddField(
            model_name='F3_Manifestation_Product_Type',
            name='volume',
            field=models.CharField(blank=True, max_length=1024, null=True)
        ),
    ]
