# Generated by Django 3.1.14 on 2022-03-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        
        ('apis_ontology', '0010_f3_subtitles_and_biblScope'),
    ]

    operations = [
        migrations.DeleteModel(
            name='F26_Recording'
        ),
        migrations.CreateModel(
            name='F26_Recording',
            fields=[
                ('e1_crm_entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.e1_crm_entity')),
                ('airing_date', models.CharField(blank=True, max_length=1024, null=True)),
                ('broadcast_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('note', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.e1_crm_entity',),
        ),
    ]
