# Generated by Django 3.1.14 on 2022-03-17 22:26

from dataclasses import Field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        
        ('apis_ontology', '0012_add_index_desc_to_f1'),
    ]

    operations = [
        migrations.AddField(
            model_name="F3_Manifestation_Product_Type",
            name="scope_style",
            field=models.CharField(blank=True, max_length=1024, null=True)
        )
    ]
