# Generated by Django 3.1.14 on 2022-03-17 22:26

from dataclasses import Field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        
        ('apis_ontology', '0013_add_scope_style_to_f3'),
    ]

    operations = [
        migrations.AlterField(
            model_name="F3_Manifestation_Product_Type",
            name="note",
            field=models.TextField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="F31_Performance",
            name="note",
            field=models.TextField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="F26_Recording",
            name="note",
            field=models.TextField(blank=True, null=True)
        )
    ]
