# Generated by Django 3.1.14 on 2022-03-17 22:26

from dataclasses import Field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        
        ('apis_ontology', '0015_model_for_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name="F3_Manifestation_Product_Type",
            name="ref_target",
            field=models.URLField(max_length=1024, blank=True, null=True)
        )
    ]
