# Generated by Django 3.1.14 on 2022-03-17 22:26

from dataclasses import Field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        
        ('apis_ontology', '0016_alter_ref_target_length'),
    ]

    operations = [
        migrations.AddField(
            model_name="F31_Performance",
            name="short",
            field=models.URLField(max_length=1024, blank=True, null=True)
        )
    ]
