# Generated by Django 3.1.14 on 2022-03-17 22:26

from dataclasses import Field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        
        ('apis_ontology', '0017_add_short_entry_for_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honour',
            fields=[
                ('e1_crm_entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.e1_crm_entity')),
                ('short', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Untertitel')),
                ('honour_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('index_in_chapter',models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.e1_crm_entity',),
        ),
        
    ]
