# Generated by Django 3.1.14 on 2023-02-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0018_add_honours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f31_performance',
            name='short',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='f3_manifestation_product_type',
            name='untertitel',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Untertitel'),
        ),
        migrations.AlterField(
            model_name='honour',
            name='short',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
