# Generated by Django 3.1.14 on 2023-04-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0019_auto_20230202_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='f3_manifestation_product_type',
            name='koha_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
