# Generated by Django 3.1.14 on 2023-04-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0020_f3_manifestation_product_type_koha_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='f26_recording',
            name='recording_type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
