# Generated by Django 3.1.14 on 2023-05-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0021_f26_recording_recording_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmlnote',
            name='context',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
