# Generated by Django 4.1.8 on 2023-06-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0024_keyword_keyword_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='f9_place',
            name='place_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
