# Generated by Django 4.1.8 on 2023-06-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0025_f9_place_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='f9_place',
            name='country',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
