# Generated by Django 4.1.10 on 2023-07-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0026_f9_place_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='e1_crm_entity',
            name='entity_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
