# Generated by Django 4.1.10 on 2023-07-27 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0027_e1_crm_entity_entity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='E38_Image',
            fields=[
                ('e1_crm_entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_ontology.e1_crm_entity')),
                ('image_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=1024, null=True)),
                ('filename', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_ontology.e1_crm_entity',),
        ),
    ]
