# Generated by Django 4.1.10 on 2023-08-01 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_relations', '0004_auto_20230124_1201'),
        ('apis_ontology', '0028_e38_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InChapterTriple',
            fields=[
                ('temptriple_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_relations.temptriple')),
                ('index_in_chapter', models.IntegerField(blank=True, null=True)),
            ],
            bases=('apis_relations.temptriple',),
        ),
    ]
