# Generated by Django 4.1.11 on 2023-09-14 07:18

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0029_inchaptertriple"),
    ]

    operations = [
        migrations.AddField(
            model_name="e1_crm_entity",
            name="vector_column_e1",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="f10_person",
            name="vector_column_f10",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="f1_work",
            name="vector_column_f1",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="f31_performance",
            name="vector_column_f31",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="f3_manifestation_product_type",
            name="vector_column_f3",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="f9_place",
            name="vector_column_f9",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="keyword",
            name="vector_column_keyword",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="xmlnote",
            name="vector_column_xmlnote",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
