# Generated by Django 4.1.11 on 2023-09-14 08:05

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0030_e1_crm_entity_vector_column_e1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="e1_crm_entity",
            name="vector_related_E40",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="e1_crm_entity",
            name="vector_related_f10",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="e1_crm_entity",
            name="vector_related_xml_content_dump",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="e1_crm_entity",
            name="vector_related_xml_note",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
