# Generated by Django 4.1.10 on 2023-09-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0031_e1_crm_entity_vector_related_e40_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='e1_crm_entity',
            old_name='vector_column_e1',
            new_name='vector_column_e1_set',
        ),
        migrations.RenameField(
            model_name='e1_crm_entity',
            old_name='vector_related_E40',
            new_name='vector_related_E40_set',
        ),
        migrations.RenameField(
            model_name='e1_crm_entity',
            old_name='vector_related_f10',
            new_name='vector_related_f10_set',
        ),
        migrations.RenameField(
            model_name='e1_crm_entity',
            old_name='vector_related_xml_content_dump',
            new_name='vector_related_xml_content_dump_set',
        ),
        migrations.RenameField(
            model_name='e1_crm_entity',
            old_name='vector_related_xml_note',
            new_name='vector_related_xml_note_set',
        ),
    ]
