# Generated by Django 4.1.10 on 2023-10-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_relations', '0004_auto_20230124_1201'),
        ('apis_ontology', '0032_rename_vector_column_e1_e1_crm_entity_vector_column_e1_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenditionTriple',
            fields=[
                ('temptriple_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_relations.temptriple')),
                ('rendition_hidden', models.BooleanField(blank=True, null=True)),
            ],
            bases=('apis_relations.temptriple',),
        ),
        migrations.RemoveField(
            model_name='f10_person',
            name='vector_column_f10',
        ),
        migrations.RemoveField(
            model_name='f1_work',
            name='vector_column_f1',
        ),
        migrations.RemoveField(
            model_name='f31_performance',
            name='vector_column_f31',
        ),
        migrations.RemoveField(
            model_name='f3_manifestation_product_type',
            name='vector_column_f3',
        ),
        migrations.RemoveField(
            model_name='f9_place',
            name='vector_column_f9',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='vector_column_keyword',
        ),
        migrations.RemoveField(
            model_name='xmlnote',
            name='vector_column_xmlnote',
        ),
    ]
