# Generated by Django 4.1.10 on 2023-10-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0033_renditiontriple_remove_f10_person_vector_column_f10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='e1_crm_entity',
            name='date_hidden',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='e1_crm_entity',
            name='title_hidden',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
