# Generated by Django 4.1.10 on 2023-10-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0034_e1_crm_entity_date_hidden_e1_crm_entity_title_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='e40_legal_body',
            name='institution_type',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
