# Generated by Django 4.1.8 on 2023-06-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericstatement',
            name='created_by',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Factoid',
        ),
    ]
