# Generated by Django 4.1.8 on 2023-06-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0002_genericstatement_created_by_delete_factoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericstatement',
            name='head_statement',
            field=models.BooleanField(default=True),
        ),
    ]
